### ISSUE TITLE
Error "Access denied" while using of kubectl in lens' terminal

### ISSUE THREAD

**Issue by rendasaev** [kontena/lens#3845]
**To Reproduce**
1. Open terminal with **+** symbol
2. Enter command **kubectl top nodes**

**Expected behavior**
kubectl should return information about resources of nodes

**Actual behavior**
```
PS C:\Users\<user> kubectl top nodes
Access denied
line:1 char:1
+ kubectl top nodes
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException
```
If I open windows powershell console (under the same user) then I get correct behavior:
```
PS C:\Users\<user> kubectl top nodes
NAME       CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
kubmcd01   501m         3%        9027Mi          28%
```

**Screenshots**
![image](https://user-images.githubusercontent.com/67231406/134067157-d91c9a74-1b64-49a7-bce2-746a30a10821.png)

**Environment (please complete the following information):**
- Lens Version: 
![image](https://user-images.githubusercontent.com/67231406/134067180-26ca0924-e25a-40b7-a20d-d59ab34b9c9c.png)
- OS: Windows 10 build 19042.1110

**Comment by ganmao** [comment]
me too

Lens: 5.2.3-latest.20210921.1
Electron: 12.0.17
Chrome: 89.0.4389.128
Node: 14.16.0

**Comment by Nokel81** [comment]
Do you lack permissions to execute binaries in `%AppData%\Lens\binaries\kubectl`?

**Comment by ganmao** [comment]
```powershell
PS C:\Users\xxxxx\AppData\Roaming\Lens\binaries\kubectl\1.21.2> .\kubectl.exe
kubectl controls the Kubernetes cluster manager.

 Find more information at: https://kubernetes.io/docs/reference/kubectl/overview/

Basic Commands (Beginner):
  create        Create a resource from a file or from stdin.
  expose        Take a replication controller, service, deployment or pod and expose it as a new Kubernetes Service
  run           Run a particular image on the cluster
  set           Set specific features on objects
...
----------------------
PS C:\Users\xxxxx\AppData\Roaming\Lens\binaries\kubectl\1.21.2> $Env:AppData
C:\Users\xxxxx\AppData\Roaming
----------------------
```
in powershell exec ok.

**Comment by sanarena** [comment]
I am also having this issue. it was working fine for first few days of installing lens in this windows server.
Reinstalling lens did not work either.

**Comment by Nokel81** [comment]
Within the terminal can you request the PATH env var? The kubectl binary should be the second entry in the PATH.

Do you have the preference set (in Lens) to use a specific version of kubectl? Does this still happen if you turn on the preference to use the bundled version of kubectl?

**Comment by sanarena** [comment]
Yes, ECHO $ENV:PATH reveal C:\Users\...\AppData\Roaming\Lens\binaries\kubectl\1.20.8;
kubectl.exe in this folder is 0kb. and unable to run with any means.
I open that folder via Explorer and tried to run the kubectl in it as administrator, which again fail: "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."

Lens Is default setting. I did not customize. It was working fine on first day. second day when i login to this remote windows server, this have happened. reinstalling lens did not solve the issue.

UPDATE: I turn off "Download kubectl binaries matching the kubernetes cluster version" and downloaded kubectl.exe manually from k8s website and give the path in PATH TO KUECTL BINARY section. it is now working fine, lens will use my own provided kubectl.exe now instead of those 0kb kubectl's inside it's C:\Users\...\AppData\Roaming\Lens\binaries\kubectl\... folder. all those kubectls in C:\Users\...\AppData\Roaming\Lens\binaries\kubectl\... folders cannot be executed but my provided kubectl.exe can be executed without an issue. This is a workaround and not a fix. please do not close the issue.

UPDATE2: If I connect to a new environment which require a different kubectl version, lens is able to download and run kubectl.exe on for that version. however it will stop after a day or two. feels like something is scanning the folders nightly and blocking the access.

**Comment by rendasaev** [comment]
Thanks @sanarena. 

> UPDATE: I turn off "Download kubectl binaries matching the kubernetes cluster version" and downloaded kubectl.exe manually from k8s website and give the path in PATH TO KUECTL BINARY section. it is now working fine

Your recept are work.
