### ISSUE TITLE
Improve Dock tabs UX

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#4459]
Currently dock tabs provide poor user experience, make it hard to work with large number of tabs. Among the problems:

* Tabs are always fixed sized despite how many of them opened
* Type icons merge with names make it harder to separate each tab from one another
* Tabs don't have visual vertical separators
* Impossible to say if tab area is scrollable or not (e. g. if more tabs opened on the right)

Browsers can be a good example of how tabs should be implemented.

Acceptance criteria:

* Selected tab should be clearly outlined from the rest
* Tabs should be switched easily with `Cmd+Tab` and other keyboard shortcuts
* Tab type should be clearly visible (make icons colorful?)
* Tabs should shrink their width to contain as much as possible in available space.
![dock tabs](https://user-images.githubusercontent.com/9607060/144046627-b002fba2-88a2-4c4d-9dfb-f18a40716761.png)

**Comment by Nokel81** [comment]
Would be nice to be able to either expand the size of tabs or scroll the tab text too.

**Comment by Nuru** [comment]
Vertical separators would be very helpful. I frequently close the wrong terminal because when viewing a tab bar like this:

![image](https://user-images.githubusercontent.com/2793313/145659133-85300a49-602b-4d60-8143-8b50ab1afe7d.png)

I get confused as to which close icon goes with which tab. 

Also, when the tab bar is longer than the window, I still don't know how to scroll it to reveal hidden tabs. I keep clicking the close icon by mistake:
![image](https://user-images.githubusercontent.com/2793313/145659349-9dd8801d-b90f-4376-ab71-0c58794bece7.png)

**Comment by DmitriyNoa** [comment]
@aleksfront @Nokel81 Material UI has pretty strong and rich Tabs components https://mui.com/components/tabs/#automatic-scroll-buttons. We can migrate to MUI Tabs. WDYT?

**Comment by aleksfront** [comment]
@DmitriyNoa Previously we decided to remove Material UI dependencies https://github.com/lensapp/lens/issues/4138. The only MUI components left in codebase are catalog Tree view and catalog Add button.
