### ISSUE TITLE
Lens in intranet

### ISSUE THREAD

**Issue by sanjesss** [kontena/lens#4616]
**What would you like to be added**:
I would like the application to understand whether there is internet on the machine or not.

**Why is this needed**:
On an intranet, lens tries to display the login page on first launch. This does not work correctly because the application is on the intranet. In this regard, I can not start work, because of the "login" sentence does not allow adding clusters to the environment.

**Environment you are Lens application on:**

- Kubernetes distribution: baremetal in intranet
- Desktop OS: Windows 10

**Comment by jweak** [comment]
@sanjesss Thanks for reporting.

This should be fixed in the next release. There's a workaround for this.

Windows:
Open  `%AppData%\Lens\extension-store\lenscloud-lens-extension`

MacOS
` ~/Library/Application\ Support/Lens/extension-store/lenscloud-lens-extension`

There should be a `startup-store.json` file. Open the file and make it: 

```json
{
	"skipSignup": true
}
```

**Comment by sanjesss** [comment]
Thanks, it's work!
For windows, after firts start:
%AppData%\**Roaming**\Lens\extension-store\lenscloud-lens-extension
