### ISSUE TITLE
Can't use terminal to pod

### ISSUE THREAD

**Issue by Inetov** [kontena/lens#4707]
**Describe the bug**
When I try to connect to pod - a window with text "Connecting ..." is appear and stuck.

I have tryed to setup another "TERMINAL SHELL PATH" in Preferenses and try with empty field - no changes.

**To Reproduce**
Steps to reproduce the behavior (in my environment):
1. Open Lens
2. Connect to cluster
3. Choose any pod and click "Pod Shell"

**Expected behavior**
Obviously - connected shell at pod)

**Screenshots**
![изображение](https://user-images.githubusercontent.com/45286374/149824685-82f7b899-daeb-420f-b8ee-284c374c78b8.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.3-latest.20211223.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): default - AppData folder. (I have checked path: AppData\Roaming\Lens\binaries\kubectl - have files)

**Logs:**
I don't understand how get it..

**Kubeconfig:**
VScode with Kubernetes extension works (including shell to pod) with this config.

**Comment by nevalla** [comment]
Does Lens terminal open properly? And does `kubectl exec ...` work on Lens terminal?

**Comment by Inetov** [comment]
I'm sorry, I don't know what it was, now it's working. Probably a tough day :)
I will reopen the issue if I find something to show

**Comment by deepybee** [comment]
> Does Lens terminal open properly? And does `kubectl exec ...` work on Lens terminal?

I realise this answer comes a year after the question but for anyone stumbling around trying to fix this I had the same issue.

It turned out (Open)Lens was trying to `source` a file that did not exist when starting the terminal, ie the invocation command was pre-set to `/bin/zsh ~./foo` - iirc `foo` looked valid enough, as in I think it was `zshrc` but as soon as I just pointed to the shell binary itself at `/bin/zsh` in the app settings the terminal sprang to life. 

You can also edit the relevant config file at `~/Library/Application\ Support/OpenLens/lens-user-store.json` (obviously substitute `OpenLens` with `Lens` if using the commercial. builds).

Maybe `foo` had a typo like `zsh_rc` or something, or maybe the shell expansion wasn't working on the tilde, I don't recall; anyway it wasn't something I'd knowingly touched.

I think this is a macOS specific thing relating to the order of precedence zsh is configured - I vaguely recall reading something odd in that regard a while back - but I could be wrong.

**Comment by OndrejKu** [comment]
I'm having the same issue on Windows 11 after the latest update to Stable. When I attempt to run shell on pod, i see the Connecting... text just like it was mentioned in the original post.

**Comment by Inetov** [comment]
> I'm having the same issue on Windows 11 after the latest update to Stable. When I attempt to run shell on pod, i see the Connecting... text just like it was mentioned in the original post.

does the target pod actually exist?
I had a case when a deployment process was running in the background and after updating the list of pods, a pod with a different identifier appeared in its place.

**Comment by OndrejKu** [comment]
Yes, this happens on every pod I've tested. Those pods are reported by others as working.

**Comment by clibequilibrium** [comment]
@OndrejKu @Inetov  as a temporary solution I just downgraded to 2023 version 

Go to https://api.k8slens.dev/binaries/Lens%20Setup%202023.9.290703-latest.exe  to get installer

Or find the patch you need 
https://forums.k8slens.dev/t/lens-2023-9-290703-latest-patch-release/1589/1

**Comment by RomanLis-GBI** [comment]
@OndrejKu running Lens as admin user helps me to resolve it.

**Comment by abbos1117** [comment]
If terminal shell is not ready please check your shell init files, if applicable.  error in Lens
