### ISSUE TITLE
Detect which resources are available if listing is not allowed

### ISSUE THREAD

**Issue by stevengubler** [kontena/lens#4893]
**What would I like to be added**: Lens should use the `SelfSubjectRulesReview` API to determine what resources to display when `list`ing a resource type is not available.

**Why is this needed**: Because expecting to always be able to `list` resources in Kubernetes breaks good practice workflows. There are many times when `list`ing should not be allowed, but where allowing other verbs like `get` for a specific resource is desirable. The `SelfSubjectRulesReview` API can help Lens compile a manifest of what those resources are, and their data can be queried for individually.

The classic example is secrets; the official documentation even specifically points out how adding `list` permissions on secrets offers ["extremely powerful capabilities and should be avoided."](https://kubernetes.io/docs/concepts/configuration/secret/#clients-that-use-the-secret-api)

---

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: MacOS

**Comment by Nokel81** [comment]
I am going to close this issue. Not because I don't think it is a good ask but because by itself it isn't very actionable. The places where we currently rely on `LIST`-ing resource where instead we can (and should) try to `GET` them instead (if not already present) are being worked on.

There are places where we GET secrets instead already.
