### ISSUE TITLE
Remove background color of cluster's icon in the hotbar

### ISSUE THREAD

**Issue by Israphel** [kontena/lens#4979]
**What would you like to be added**:
Allow me to remove the background color of cluster's icon in the hotbar.

**Why is this needed**:
I picked icons with transparent background because they looked nice in Lens, but now they got random colors.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: OSX

**Screenshot**:
![Screen Shot 2022-03-07 at 18 52 56](https://user-images.githubusercontent.com/720191/157124218-ace54879-25e1-492b-9e92-5c02178b110d.png)

**Comment by Kolossi** [comment]
I would like to second this, I have custom icons, and the enforced "random" colours completely messes them up as I also left transparent background to work with whatever Lens UI used.

---

Added to that (yes it should probably be a separate issue, but I'm not raising it as I don't actually want the background colours) - many of the "random" colours are VERY similar to each other and so are not useful for differentiating clusters anyway!

You probably need to implement a colour generator something like this:

```python
def getRGBColours(numColours):
    colours=[]
    for i in xrange(0,numColours):
        hue=(i+0.5)/float(numColours)
        colour=HSVtoRGB(hue,1.0,1.0)
        colours.append(colour)
    return colours
```
The implementation of HSVtoRGB() left as an exercise for the reader :-) - just so I don't have to past a wall of code if it's not wanted, but there's plenty of implementations on t'internet.

**Comment by Nokel81** [comment]
Marking this as a bug since it is actually a regression. Probably from https://github.com/lensapp/lens/pull/2608.

**Comment by Nokel81** [comment]
@Kolossi Being able to pick the colour yourself is covered by https://github.com/lensapp/lens/issues/3846

**Comment by Kolossi** [comment]
@Nokel81 sure, and not disagreeing with what you've said or done.

But as in #2608 it's helpful to have auto-assigned colours for those that don't want to make their own icon but ISTM that the auto-colour-picking is pretty flawed as-is, that's why I suggest the above algorithm which is guaranteed to "space" the colours so that they can be differentiated.  I guess that's an enhancement to #2608 really.

But when someone _has_ designed their own custom icon the background to that icon display should absolutely only be the UI background, nothing else.  I guess that's the bug fix that are proposing for this issue?

**Comment by Nokel81** [comment]
Spacing out the colours is a good idea. Yeah, the bug that was introduced was having the background colours also apply to icons with transparency.
