### ISSUE TITLE
terminal font family other than RobotoMono have large char spacing

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#5133]
Even monospaced fonts like CourierNew seem to have too large spacing between characters:

![Screen Shot 2022-03-29 at 10 43 15 AM](https://user-images.githubusercontent.com/40840436/160644825-e66fee03-03da-42b0-ba9e-815fc7f8e51e.png)

Only RobotoMono has correct spacing

happens on 5.4.4

**Comment by ixrock** [comment]
It looks like it's not even loaded properly and browser decided to throw at least something :)

**Comment by ixrock** [comment]
@jim-docker  so which fonts do we support for terminal? 

Currently it seems only `string fontFamily` and `number fontSize` are available in user settings for changing this option. 
What if we limit available fonts for terminal to 5 and show in the select-box? 
_Reason:_ because we probably need to configure more css rules per supported terminal font to show it properly? Wdyt?
