### ISSUE TITLE
Incorrect metrics in UI for Nodes and Pods

### ISSUE THREAD

**Issue by lavkhanna** [kontena/lens#5140]
**Describe the bug**
All the metrics in Lens UI are double the actual amount. The cluster is using `prometheus-operator` with Auto Detect in Metrics settings for the cluster. 

AWS t2.medium is 2vCPU and 4GB ram. However, the metrics is showing 4vcpu and 8GB ram. This is happening with all monitored resource like Node and Pods.

**Expected behavior**
Expected behavior is to get correct metrics in the UI.

**Screenshots**
![Screenshot 2022-03-29 at 12 35 27 PM](https://user-images.githubusercontent.com/91055008/160749785-d4218f92-9858-4844-a195-86b26421057a.png)

**Environment (please complete the following information):**
- Lens Version: 5.4.4-latest.20220325.1
- OS: MacOS BigSlur 11.3.1
- Installation method (e.g. snap or AppImage in Linux): dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [CONTEXT-HANDLER]: using operator as prometheus provider for clusterId=XXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by aleksfront** [comment]
I'm thinking can it be similar to this issue https://github.com/lensapp/lens/issues/807? Is it possible that some deployment which provides metrics is scaled?

**Comment by lavkhanna** [comment]
@aleksfront  Thanks. You are right.
I actually have two jobs that are exporting the metrics. 
```
kubecost-cost-analyzer ---> Coming from KubeCost
kube-prometheus-stack-kube-state-metrics ---> Coming from Kube-prometheus-stack
```
Is it possible in Lens to customize the query Lens does on Prometheus ?

**Comment by Nokel81** [comment]
@lavkhanna Not currently. There is https://github.com/lensapp/lens/issues/3955 but I don't think that matches exactly what you want.

Might be useful to be able to pick one of the jobs even in "Auto Detect" mode.

**Comment by lavkhanna** [comment]
@Nokel81  Yes, #3955 would do the job for us.

I dont think there would be any problem if Lens picked up one of the jobs. As compared to now, where there is addition happening.

**Comment by jhoelzel** [comment]
I have the same issue, even when i set the metrics directly to the prometheus endpoint ( monitoring/prometheus:9090 ) .
I also habe kubecost running, and its using monitoring/prometheus:9090 as well, my first guess is that the kube-state-metrics have to be deactivated separately over the helm chart (im using helm) of kubecost

**Comment by jhoelzel** [comment]
Update:
i deactivated the additionl kube-state-metrics through the helm chart of kubecost, but it still yields the same result, double metrics in lens when set to prometheus operator mode or in fact any other too. 

Grafana does not have this problem at all so i still believe the problem lies with lens :/

**Comment by lavkhanna** [comment]
@jhoelzel Disabling worked for me though. I am using this HelmChart 
```
chart: cost-analyzer
version: '1.91.2'
```

With the following values:
```
global:
      prometheus:
        enabled: false
prometheus:
      kube-state-metrics:
        disabled: true
      nodeExporter:
        enabled: false
```
But this would actually break my kubecost 😢

**Comment by jhoelzel** [comment]
as an update i figured it out. The cost-model deployment of kubecost is actually exposing the metrics twice and that is what is picked up by prometheus in the end. 

A detailed description can be found here: 
https://guide.kubecost.com/hc/en-us/articles/4408095797911-Kube-State-Metrics-KSM-Emission

but a tldr: cost-model is exposing way more metrics than it should which has to be disabled in order to not get metrics twice. so this actually has nothing to do with lens, but is all about kubecost.

What i ended up doing is to convert the helm release to kustomize und deploying the cost-model container in kombination with the env vars mentioned in the article.
