### ISSUE TITLE
Cluster Connect | Team Members Unable to Access Cluster

### ISSUE THREAD

**Issue by rgutwein** [kontena/lens#5300]
Having issues with my team accessing the cluster connect feature in Lens. I am guessing this has to do with the ~/Kubeconfig file - currently using mini kube on M1 and I created a teams space - and allowed access to specific users. They can see the teams space but cannot access the cluster.

I think what happens..still doing some research.. but when you add a cluster it pulls off your kube.config. when you create your space I think you need a new config that then shares throughout the space. When my team tries to access the clusters I shared it gives them an SSL error which is directly from the config.

When you go to your space I think it pulls your config... I think what needs to happen is you pull a new config in the space and promote it. Then the users you invite to the space use the same and you resolve the proxy error.

Please advise

**Expected behavior**
Expected team members to have access to the cluster after sending them invite to connect to the cluster.

**Screenshots**
![image](https://user-images.githubusercontent.com/51237807/166113173-4e6461a1-c8a7-4ff6-95a0-2cf985a3818e.png)

**Environment (please complete the following information):**
- Lens Version: Lens: 5.4.6-latest.20220428.1
- OS: Mac M1
- Installation method: minikube

**Kubeconfig:**
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <>
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority-data: <>
    server: https://127.0.0.1:62663
  name: kind-kind
- cluster:
    certificate-authority: /Users/<username>/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Fri, 29 Apr 2022 19:12:21 EDT
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: https://127.0.0.1:53489
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 29 Apr 2022 19:12:21 EDT
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: <>
- name: kind-kind
  user:
    client-certificate-data: <>
    client-key-data: <>
- name: minikube
  user:
    client-certificate: file path
    client-key: file path

**Comment by chenhunghan** [comment]
@rgutwein Hello, from the screenshot you attached, the problem seems to be on your team's machine.

Assuming they are using Windows, is this file `C:\Users\kulas\AppData\Local\Program\Lens\resources\extensions\lenscloud-lens-extension\dist\lens-spaces-authenticator` missing? This could because of a broken Lens version installed.

Can you please tell them to reinstall latest stable Lens (currently 5.4.6), and try again? https://k8slens.dev

**Comment by judechen-bhp** [comment]
I had the exact same issue with the freshly installed 5.4.6 latest version on my Windows 11 laptop too. I followed the path trying to locate the `lens-spaces-authenticator` binary file, and found there were only `lens-spaces-authenticator-x64.exe` and `lens-spaces-authenticator-arm64.exe`. So I tried to rename the `lens-spaces-authenticator-x64.exe` to `lens-spaces-authenticator.exe` and then the issue was gone! Is this a bug for the Windows version? 
![image](https://user-images.githubusercontent.com/72418673/168378179-5f3ea573-e20e-4fff-a712-34eb9c0acc87.png)
