### ISSUE TITLE
Does Lens support remote hosts?

### ISSUE THREAD

**Issue by ichoosetoaccept** [kontena/lens#5435]
I'm in a corporate environment. I have to SSH to a remote host from which I then do kubectl login and can then access my clusters. Does Lens support such a setup?

**Comment by philipshannon** [comment]
I use Lens in exactly this way. Run it on my laptop in a corp environment, it's a central place for managing all of the k8s clusters. 

Just connect to your remote systems via ssh and get the required info via "kubectl config view --minify --raw", copy/paste this into Lens.

**Comment by ichoosetoaccept** [comment]
I wish it were that simple.

My company uses its own MFA solution (a bank) and I think this is where this fails. We get K8S as a service and I only get to manage the namespace for my application. Perhaps I'm just not meant to use Lens...

When I try what you suggested I get "Error while proxying request: x509: certificate signed by unknown auhority"

**Comment by ichoosetoaccept** [comment]
> I use Lens in exactly this way. Run it on my laptop in a corp environment, it's a central place for managing all of the k8s clusters. 
> 
> 
> 
> Just connect to your remote systems via ssh and get the required info via "kubectl config view --minify --raw", copy/paste this into Lens. 
> 
> 

You said "run it on my laptop in a corp environment, it's a central place for managing all of the k8s clusters."

The difference with me is... I don't run kubectl on my laptop. I first have to ssh to a bastion just with custom auth. by my employer, and then, once connected, do kubectl login, MFA authenticate AGAIN, and then and only then I have access to kubectl, or said differently, the Kubernetes API.

**Comment by philipshannon** [comment]
Got it! Should have known it couldn't be this easy, but works simply for me. Sorry that you face extra security hurdles.

**Comment by ichoosetoaccept** [comment]
Perhaps I could get it to work with SSH tunneling to the bastion host, but I don't think I *should* be trying that...

**Comment by jim-docker** [comment]
@ichoosetoaccept Are you accessing your clusters via `kubectl` strictly from the remote system, or running `kubectl` from your local machine once you've set things up/logged in on the remote system? And where are you running Lens from?

**Comment by ichoosetoaccept** [comment]
Lens from my Mac, and kubectl strictly from the bastion host once ssh'd into it. I assume the company set it up this way for security reasons as everything is monitored on the bastion host.
There's also a custom 2FA on the remote host that I authenticate against with an SMS code.

**Comment by jim-docker** [comment]
If you can't connect to a cluster using `kubectl` on your mac then it is highly unlikely that you can connect to a cluster using Lens on your mac (Lens relies on the same kubeconfig that `kubectl` uses). You'd probably need to open something on the bastion to let you do that.

Alternatively, if you can install Lens on the bastion it should work (since `kubectl` works from there). You would need an X server (like XQuartz) installed on your mac to see the Lens UI. You would use the `-Y` option when you ssh into the bastion (if it allows it). I have used this setup successfully to connect remotely. Good network bandwidth is required for a responsive Lens UI. Also, see https://docs.k8slens.dev/main/faq/#does-lens-work-over-x11
