### ISSUE TITLE
Can`t open application when using proxy

### ISSUE THREAD

**Issue by ozcolumbus** [kontena/lens#5482]
**Describe the bug**
Can`t open application and setup proxy settings. Can`t see where to navigate to enter proxy settings

**To Reproduce**
Run software when you are behind proxy.

**Screenshots**
![Screenshot 2022-05-27 174216](https://user-images.githubusercontent.com/25272151/170722275-23f8cacf-a495-4dc5-870a-a00e9a873f17.jpg)

**Comment by Nokel81** [comment]
@nevalla @chenhunghan

**Comment by UnasZole** [comment]
I confirm seeing the same issue, along with all of my colleagues, when we updated to the latest Lens version (while being a corporate proxy).
Downgrading worked fine.

**Comment by snauhaus** [comment]
@UnasZole could you point me toward an older installer? I can only find the most recent version online

**Comment by UnasZole** [comment]
Ha. while searching about this error, I just noticed it comes from the recent decision to make Lens IDs mandatory (cf. https://twitter.com/k8slens/status/1529470612380344321 ), since it's the initial check for a Lens ID that fails to use proper proxy settings.
Well, if that's it, then don't bother fixing it on my part - we'll keep using an older version until another tool like Octant fully catches up.

@snauhaus  For the time being, release 5.4.6 (the last one before all this mess) is still available here : https://lens-binaries.s3-eu-west-1.amazonaws.com/ide/Lens%20Setup%205.4.6-latest.20220421.1.exe
Just downloaded and installed it, and it runs like a charm.
I advise you to save it preciously somewhere, since they might suddenly decide to remove old version from this aws cache.

**Comment by msa0311** [comment]
We are really sorry for the circumstances, it was definitely the not our intention to block offline or air gapped use cases. We introduced a check that will let you pass by the Lens ID registration.
Would you mind trying our latest version and provide feedback if that solved the problem you faced?

**Comment by jim-docker** [comment]
fixed in latest stable release
