### ISSUE TITLE
Hotbar switching no longer displays name as tooltip

### ISSUE THREAD

**Issue by Nokel81** [kontena/lens#5517]
Regression after https://github.com/lensapp/lens/pull/4679

The tooltip which should show up when switching hotbars via the arrows no longer shows up in 5.5.2

**Comment by sujith0408** [comment]
Hi Nokel, is there a way by which either the icon can be uploaded or the cluster name can be displayed on the hotbar in a format like Environment-KC-Region e.g. UT-KC-USE2 instead of the current Profile format which displays only 3 characters, where UT represents UAT, KC represents K8S cluster depiction, USE2 represents US East2 region. And the requirement is to have a uniform view available across the team.
