### ISSUE TITLE
Terminal is broken in latest master

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#5637]
![terminal errors](https://user-images.githubusercontent.com/9607060/173783963-1dd148fa-6973-42ea-b68c-1d195cb388c1.png)

https://user-images.githubusercontent.com/9607060/173784007-b63c1a88-bd1b-4aaa-8320-d464c629b7fb.mov

**Comment by jerch** [comment]
This is due to `FitAddon.proposeDimensions()` being incompletely typed (see https://github.com/xtermjs/xterm.js/issues/3881).

In general calling `proposeDimensions` yourself should not be needed - `FitAddon.fit()` already does it internally (with correctly handling the edge cases). Rework suggestion (untested, scoping might be wrong/needs dispose etc.):
```typescript
  fit = () => this.fitAddon.fit();

  // when fit triggered a real terminal resize, xterm.js will fire onResize event,
  // just grab that and forward it
  this.xterm.onResize((size: { cols: number, rows: number }) => {
    this.api.sendTerminalSize(size.cols, size.rows);
  });
```

**Comment by Nokel81** [comment]
@jerch The problem is that we run into https://github.com/xtermjs/xterm.js/issues/3118

**Comment by jerch** [comment]
@Nokel81 Oh well, there is a possibility of `ITerminalDimensions` containing  `{cols: NaN, rows: NaN}` from `proposeDimensions`, which would trigger the error described in https://github.com/xtermjs/xterm.js/issues/3118 in `term.resize`. This sadly cannot be narrowed further with typescript, but imho should be fixed upstream in `proposeDimensions` by just returning `undefined` if any value ended up as NaN (see comment there).

As a quick workaround, maybe just keep the exception handler in place for now:

```typescript
  fit = () => {
    try {
      this.fitAddon.fit();
    } catch (e) {
     logger.error(`[TERMINAL]: failed to resize terminal to fit`, e);
    }
  };

  // when fit triggered a real terminal resize, xterm.js will fire onResize event,
  // just grab that and forward it
  this.xterm.onResize((size: { cols: number, rows: number }) => {
    this.api.sendTerminalSize(size.cols, size.rows);
  });
```

Edit: This should already be fixed in recent fit addon version, so the exception handler should be obsolete.
