### ISSUE TITLE
Resizing dock resets install helm chart loading state

### ISSUE THREAD

**Issue by Nokel81** [kontena/lens#6053]
https://user-images.githubusercontent.com/8225332/185479854-1b53582d-0c3d-4c97-92a1-4b71191b114b.mov

**Comment by aleksfront** [comment]
It's a bit more serious issue that just disappeared "Install..." message. It turns out that on dock resize all inner elements gets recreated with full cycle (`componentDidMount` and `componentWillUnmount`) on every `onResize` tick including heavy monaco editor. That's why I've set close milestone to it.

**Comment by aleksfront** [comment]
https://user-images.githubusercontent.com/9607060/186413511-dcb5b714-3e05-48ea-ad04-28a7ce550f75.mov
