### ISSUE TITLE
Error: unknown command "oidc-login" for "kubectl"

### ISSUE THREAD

**Issue by LinTechSo** [kontena/lens#6317]
## problem 

I installed LENS with ` sudo snap install kontena-lens --classic` command from the snap store
 My  Kubernetes clusters have OIDC 

![Screenshot_2022-10-04_20-56-54](https://user-images.githubusercontent.com/53074289/193886489-1cd460a0-13d8-4f7a-a2e1-adc95856a1a3.png)

Any updates ?

**Comment by nabokihms** [comment]
Same problem here. Any help? I can provide any debug info.

**Comment by tapanhalani** [comment]
Same issue on my end too, my cluster is local microk8s configured with oidc . I can also provide debug info if needed.

**Comment by Nokel81** [comment]
FYI the snapstore version is currently extremely out of date. The latest version can be downloaded via k8slens.dev and has some fixes regarding this, can you try the latest version and see if that resolves this issue?

**Comment by AlexanderSarson** [comment]
same problem here.
oidc-login installed with krew and kubectl commands works but lens doesn't

I'm on Windows though

**Comment by Nokel81** [comment]
@AlexanderSarson What version are you using? Have you quit the tray icon recently?

**Comment by AlexanderSarson** [comment]
@Nokel81 You were right. it was the tray icon - it works now, thanks :)

**Comment by Nokel81** [comment]
There is currently not a known way to get the current "root environment" on Windows so we don't refresh it ever.

**Comment by nabokihms** [comment]
https://github.com/lensapp/lens/issues/6317#issuecomment-1280818650
I am on Mac and installed Lens from the official website. If there is any information I can provide to help with debugging, please tell me.

**Comment by Nokel81** [comment]
1. What shell are you using?
2. Do you see a notification about failing to sync shell env vars?
3. Logs are at `~/Library/Logs/Lens`

**Comment by nabokihms** [comment]
@Nokel81 
1. zsh
2. Nothing like this
3. The message was the same: unknown command "oidc-login" for "kubectl".

BTW, I upgraded Lens and no everything works as expected. I do not know what actually fixed the problem.

**Comment by Nokel81** [comment]
We did some improvements to how is is synced so maybe that helped it.

Glad your setup is writing though.

**Comment by Nokel81** [comment]
`kontena-lens` snap is unsupported. Please upgrade.

**Comment by demsking** [comment]
Check this: https://github.com/int128/kubelogin/issues/685#issuecomment-1372165422

**Comment by hequ** [comment]
In case someone stumbles into this in the future, my problem was that I installed `oidc-login` with krew, and open-lens could not find the krew plugins because the krew binary path was missing from my `$PATH`. The binary path was missing because I use fish as my default shell (and I have set the environment for fish correctly), but when  I launch the open-lens via gnome, it does not load the fish settings, but it reads the settings from the .profile

The fix was to add the krew binaries to the path.

Add to your `.profile`:

```bash
# Add krew
export PATH="$PATH:$HOME/.krew/bin"
```

then logout, and log back in, and open-lens should be able to find plugins installed with krew.

**Comment by hequ** [comment]
I'm writing this in case someone stumbles into this in the future. I had a similar issue with open-lens and I resolved it by fixing the $PATH.

My problem was that I installed `oidc-login` with krew, and open-lens could not find the krew plugins because the krew binary path was missing from my `$PATH`. The binary path was missing because I use fish as my default shell (and I have set the environment for fish correctly), but when  I launch the open-lens via gnome, it does not load the fish settings, but it reads the settings from the .profile

The fix was to add the krew binaries to the path.

Add to your `.profile`:

```bash
# Add krew
export PATH="$PATH:$HOME/.krew/bin"
```

then logout, and log back in, and open-lens should be able to find plugins installed with krew.

**Comment by atassis** [comment]
@Nokel81 stated, that `kontena-lens` is not supported, though [official documentation](https://docs.k8slens.dev/getting-started/install-lens/#snap) states that it is an option
