### ISSUE TITLE
K8s api watch does not retry

### ISSUE THREAD

**Issue by jakolehm** [kontena/lens#6635]
```
[KUBE-API] watch (event-7) started /api/v1/namespaces/xxx/events?watch=1&resourceVersion=162063
[KUBE-API] watch (pod-6) started /api/v1/namespaces/xxx/pods?watch=1&resourceVersion=162063
[KUBE-API] watch (event-7) aborted /api/v1/namespaces/xxx/events?watch=1&resourceVersion=162063
[KUBE-API] watch (pod-6) aborted /api/v1/namespaces/xxx/pods?watch=1&resourceVersion=162063
... stops here ...
```

**Comment by HeneryHawk** [comment]
Hi,

I noticed that, for example, the status of the pods does not update after a while, or new namespaces do not appear. Only a disconnect and reconnect with the cluster leads to an update. After a while the problem starts again.

Is this due to this issue?
Otherwise i will create a new one as it was working with a older version.

Version: 6.2.1
OS: Windows
K8s Version: 1.23.8

Regards
