### ISSUE TITLE
Blank window when cluster disconnected

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#6934]
We see blank view instead of Catalog when disconnected from active cluster.

Tested with minikube with M1 machine.

https://user-images.githubusercontent.com/9607060/212269227-54a7afce-1d50-468a-857c-05fe5b4500b1.mov

![v8 fatal error](https://user-images.githubusercontent.com/9607060/212269238-ca66ce74-8737-4992-b9b7-5b48228e821b.png)

**Comment by clrothmann** [comment]
I am not able to reproduce on my M1 machine -> Lens: 2023.1.110749-latest

**Comment by alebcay** [comment]
I am able to reproduce this with 6.4.0-alpha.2 on macOS (Intel) and a minikube cluster. If you open developer tools, they also get disconnected from the application when disconnecting from a cluster.

Reloading the view and then going to catalog (via the application menu, since hotbar is missing) seems to recover back to a working state.
